VolantProject/VolantProject/urls.py
from django.contrib import admin
from django.urls import path
from VolantApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='landinghome'),
    path('userregister/',views.UserRegisterView.as_view(),name='user_register'),
    path('userlogin',views.UserLogin.as_view(),name='user_login'),
    path("userlogout",views.Userlogout.as_view(), name="logout"),
    path('index/',views.UserIndex.as_view(),name='user_index'),
    path('gentsview/',views.GentsProductsView.as_view(),name='gentsview'),
    path('ladiesview/',views.LadiesProductsView.as_view(),name='ladiesview'),
    path('bgview/',views.GirlsBoysProductsView.as_view(),name='bgview'),
    path('kidsview/',views.KidsProductsView.as_view(),name='kidsview'),
    path('usergentsview/',views.UserGentsProductsView.as_view(),name='usergentsview'),
    path('userladiesview/',views.UserLadiesProductsView.as_view(),name='userladiesview'),
    path('userbgview/',views.UserGirlsBoysProductsView.as_view(),name='userbgview'),
    path('userkidsview/',views.UserKidsProductsView.as_view(),name='userkidsview'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('contact/',views.ConatctView.as_view(),name='contact'),
    path('userabout/',views.UserAboutView.as_view(),name='userabout'),
    path('usercontact/',views.UserConatctView.as_view(),name='usercontact'),
    path("terms/", views.TermsAndConditons.as_view(), name="terms"),
    path("privacy/", views.PrivacyPolicy.as_view(), name="privacy"),
    path('detail/<int:id>',views.ProductDetailView.as_view(),name='detail'),
    path('userdetail/<int:id>',views.UserProductDetailView.as_view(),name='userdetail'),
    path('addtocart/<int:id>',views.AddToCartView.as_view(),name='addtocart'),
    path('list/',views.CartListView.as_view(),name='list'),
    path('adminpage/',views.AdminIndexView.as_view(),name='adminpage'),
    path('adminproducts/',views.AdminProductListView.as_view(),name='adminproducts'),
    path('addpro/',views.AdminAddProductView.as_view(),name='add_pro'),
    path('update/<int:id>',views.AdminUpdateProductView.as_view(),name='update_pro'),
    path('image/<int:id>',views.AdminAddimage.as_view(),name='image'),
    path('size/<int:id>',views.AdminAddSize.as_view(),name='size'),
    path('cart/remove/<int:id>',views.RemoveCartItem.as_view(),name='cart_remove'),
    path('buy/<int:id>',views.BuyNowView.as_view(),name='buy_view'),
    path('adminorderlist/',views.AdminOrderList.as_view(),name='adminorderlist'),
    path('adminordersdetail/<int:id>',views.AdminOrdersDetail.as_view(),name='adminordersDetail'),
    path('adminorderupdate/<int:id>',views.AdminUpdateOrderView.as_view(),name='adminorderupdate'),
    path('admindelepeproduct/<int:id>',views.AdminDeleteProductView.as_view(),name='admindelepeproduct'),
    path('userorderlist',views.UserOrderView.as_view(),name='userorderlist'),
    path('orderdelete/<int:id>',views.RemoveOrderItem.as_view(),name='orderdelete'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VolantProject/VolantApp/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.

class Footwears(models.Model):
    product_options=(
        ('sandals','sandals'),
        ('slipperandflipflops','slipperandflipflops'),
        ('casualshoes','casualshoes'),
        ('specialcollections','specialcollections'),
        ('flatshoes','flatshoes'),
        ('schooledition','schooledition'),
    )
    product_category=models.CharField(max_length=100,choices=product_options)
    types=(
        ('ladies','ladies'),
        ('gents','gents'),
        ('boys','boys'),
        ('girls','girls'),
        ('kids','kids')
    )
    product_types=models.CharField(max_length=100,choices=types)
    product_name=models.CharField(max_length=100)
    product_price=models.FloatField()
    product_description = models.TextField()
    colors=(
        ('Black','Black'),
        ('Blue','Blue'),
        ('Brown','Brown'),
        ('Camel','Camel'),
        ('Cherry','Cherry'),
        ('Gold','Gold'),
        ('Grape','Grape'),
        ('Green','Green'),
        ('Grey','Grey'),
        ('Maroon','Maroon'),
        ('Mehandi','Mehandi'),
        ('Navy','Navy'),
        ('Olive','Olive'),
        ('Peach','Peach'),
        ('Peacock','Peacock'),
        ('Pink','Pink'),
        ('Purple','Purple'),
        ('Tan','Tan'),
        ('Violet','Violet'),
        ('White','White'),
        ('Wine','Wine'),
        ('Yellow','Yellow'),
    )
    product_color=models.CharField(max_length=100,choices=colors)
    image = models.ImageField(upload_to='images/')
    
    def __str__(self):
        return self.product_name
    
    
class Footwearimages(models.Model):
    product=models.ForeignKey(Footwears,on_delete=models.CASCADE)
    colors=(
        ('Black','Black'),
        ('Blue','Blue'),
        ('Brown','Brown'),
        ('Camel','Camel'),
        ('Cherry','Cherry'),
        ('Gold','Gold'),
        ('Grape','Grape'),
        ('Green','Green'),
        ('Grey','Grey'),
        ('Maroon','Maroon'),
        ('Mehandi','Mehandi'),
        ('Navy','Navy'),
        ('Olive','Olive'),
        ('Peach','Peach'),
        ('Peacock','Peacock'),
        ('Pink','Pink'),
        ('Purple','Purple'),
        ('Tan','Tan'),
        ('Violet','Violet'),
        ('White','White'),
        ('Wine','Wine'),
        ('Yellow','Yellow'),
    )
    product_color=models.CharField(max_length=100,choices=colors)
    product_image=models.ImageField(upload_to='imagesall/',null=True,blank=True)
    
class Footwearsize(models.Model):
    product = models.ForeignKey(Footwears, on_delete=models.CASCADE)
    sizes = (
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
        ('5','5'),
        ('6','6'),
        ('7','7'),
        ('8','8'),
        ('9','9'),
        ('10','10'),
        ('11','11'),
        ('12','12'),
        ('13','13'),
    )
    size = models.CharField(max_length=100, choices=sizes)

class CartModel(models.Model):
    product = models.ForeignKey(Footwears, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choices = (
        ('in_cart', 'in_cart'),
        ('order_placed', 'order_placed'),
        ('cancelled', 'cancelled'),
    )
    status = models.CharField(max_length=100, choices=choices, default='in_cart')
    size = models.ForeignKey(Footwearsize, on_delete=models.CASCADE)
    color = models.ForeignKey(Footwearimages, on_delete=models.CASCADE)
    total = models.FloatField()
    
    def __str__(self):
        return f"Product: {self.product}, Color: {self.color}, Size: {self.size}"
    

class CartModel(models.Model):
    product = models.ForeignKey(Footwears, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choices = (
        ('in_cart', 'in_cart'),
        ('order_placed', 'order_placed'),
        ('cancelled', 'cancelled'),
    )
    status = models.CharField(max_length=100, choices=choices, default='in_cart')
    size = models.ForeignKey(Footwearsize, on_delete=models.CASCADE)
    color = models.ForeignKey(Footwearimages, on_delete=models.CASCADE)
    total = models.FloatField()
    
    def __str__(self):
        return f"Product: {self.product}, Color: {self.color}, Size: {self.size}"
    

class OrderModel(models.Model):
    product = models.ForeignKey(Footwears, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    color = models.ForeignKey(Footwearimages, on_delete=models.CASCADE)
    size = models.ForeignKey(Footwearsize, on_delete=models.CASCADE)
    options={
        ('order-placed','order-placed'),
        ('dispatched','dispatched'),
        ('shipped','shipped'),
        ('delivered','delivered'),
        ('cancelled','cancelled')
    }    
    status=models.CharField(max_length=100,choices=options,default='order-placed')
    quantity = models.IntegerField(default=1)
    phone = models.CharField(max_length=100)
    email =models.EmailField(max_length=254)
    address = models.TextField()
    total = models.FloatField()
    
    def __str__(self):
        return f"Product: {self.product}, Color: {self.color}, Size: {self.size}"
    

VolantProject/VolantApp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import CartModel, Footwearimages,Footwears,Footwearsize,OrderModel

class UserRegisterForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['first_name','last_name','email', 'username','password']
        widgets = {
            'password': forms.PasswordInput(attrs={'class':'form-control bg-transparent  p-2 my-2 regin','placeholder':'Enter Password'}),
            'first_name': forms.TextInput(attrs={'class':'form-control bg-transparent  p-2 my-2 regin','placeholder':'Enter First Name'}),
            'last_name': forms.TextInput(attrs={'class':'form-control bg-transparent  p-2 my-2 regin','placeholder':'Enter last Name'}),
            'username': forms.TextInput(attrs={'class':'form-control bg-transparent  p-2 my-2 regin','placeholder':'Enter Username'}),
            'email': forms.TextInput(attrs={'class':'form-control bg-transparent  p-2 my-2 regin','placeholder':'Enter Email'}),
        }

class UserLoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','password']
        widgets = {
            'password': forms.PasswordInput(attrs={'class':'form-control bg-transparent  p-2 my-2 regin','placeholder':'Enter Password'}),
            'username': forms.TextInput(attrs={'class':'form-control bg-transparent  p-2 my-2 regin','placeholder':'Enter Username'}),
        }

class CartForm(forms.ModelForm):

    class Meta: 
        model = CartModel
        fields = ['quantity',]
        widgets = {
            'quantity': forms.NumberInput(attrs={'class':'form-control w-25','placeholder':'','max':'5','min':'1'}),
        } 
        
        

class FootwearsForm(forms.ModelForm):
    class Meta:
        model = Footwears
        fields = '__all__'
        widgets={
            'product_category':forms.Select(attrs={'class':'form-select w-25 paddform'}),
            'product_types':forms.Select(attrs={'class':'form-select w-25 paddform'}),
            'product_name':forms.TextInput(attrs={'class':'form-control w-25 ','placeholder':'Footwear Name'}),
            'product_price': forms.NumberInput(attrs={'class': 'form-control w-25', 'placeholder': 'Product Price'}),
            'product_description':forms.Textarea(attrs={'class':'form-control paddform','placeholder':'enter the description'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control w-25'}),
            'product_color':forms.Select(attrs={'class':'form-select w-25 paddform'}),
        }

class FootwearimagesForm(forms.ModelForm):
    class Meta:
        model = Footwearimages
        fields = ['product_image','product_color']
        widgets = {
            'product_image': forms.ClearableFileInput(attrs={'class': 'form-control w-50'}),
            'product_color':forms.Select(attrs={'class':'form-select w-50 paddform'}),
        }
        
class FootwearSizeForm(forms.ModelForm):
    class Meta:
        model = Footwearsize
        fields = ['size']
        widgets = {
            'size':forms.Select(attrs={'class':'form-select w-25 paddform'}),
        }

class OrderForm(forms.ModelForm):
    class Meta:
        model = OrderModel
        fields = ['quantity','phone','email','address']
        widgets = {
            'quantity': forms.NumberInput(attrs={'class':'form-control w-25','placeholder':'','max':5,'min':1}),
            'phone':forms.TextInput(attrs={'class':'form-control w-100','placeholder':'Enter your number','maxlength':10,'minlength':10}),
            'email':forms.EmailInput(attrs={'class':'form-control w-100','placeholder':'enter email'}),
            'address':forms.TextInput(attrs={'class':'form-control w-100','placeholder':'address'})
        }
class AdminOrderForm(forms.ModelForm):
    class Meta:
        model = OrderModel
        fields = ['status']
        widgets = {
            'status':forms.Select(attrs={'class':'form-select w-25 paddform'}),
        }
        

VolantProject/VolantApp/templates/8addticart.html
{% extends '7userproductview.html' %}

{% block content %}
<style>
    @media (max-width: 600px) {
        input{
            width: 100% !important;
        }
    }
    input{
        width: 25% !important;
    }
</style>

<section class="main-banner container" id="#top">
    <div class="">
        <div class="row">
            <div class="col-md-6 ">
                <div class="row p-img-div">
                    <img src="{{ product.image.url }}" alt="" class="p-s-img" id="ProPurImage">
                </div>
                <!-- <div class="row subimgs-row">
                    <img src="{{ product.image.url }}" alt="">
                    <img src="{{ product.image.url }}" alt="">
                    <img src="{{ product.image.url }}" alt="">
                    <img src="{{ product.image.url }}" alt="">
                </div> -->
            </div>
            <div class="col-md-6 ">
                <div class="p-img-details">
                    <h3 class="ms-2 text-capitalize">{{product.product_types}} {{product.product_category}} {{product.product_name}}</h3>
                    <p class="ms-2 mt-2">₹ {{ product.product_price }}</p>
                </div>
                <div class=" p-detail p-4">
                    
                    <div class="i-size">
                        <form method="POST">
                            {% csrf_token %}
                            <!-- Quantity input -->
                             {{form}}
                            
                            <!-- Color selection -->
                            <label for="product_color">Color:</label>
                            <select id="product_color" name="product_color" class="form-select w-50 text-uppercase">
                                {% for color in product.footwearimages_set.all %}
                                    <option value="{{ color.id }}" name="color_id"  class="text-uppercase">{{ color.product_color }}</option>
                                {% endfor %}
                            </select>
                            <!-- Size selection -->
                            <label for="size">Size:</label>
                            <select id="size" name="size" class="form-select w-50">
                                {% for size in product.footwearsize_set.all %}
                                    <option value="{{ size.id }}" name="size_id">{{ size.size }}</option>
                                {% endfor %}
                            </select>
                            
                            <button type="submit" class="buy-btn btn mt-3">Add to cart</button>
                        </form>
                        <div class="cart-buy-btn row mt-3 flex-wrap justify-content-center">
                            
                            <div class="mb-3 mt-3 w-100">

                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-6">
                <div class="accordion accordion-flush" id="accordionFlushExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapseOne" aria-expanded="false"
                                aria-controls="flush-collapseOne">
                                Product Details
                            </button>
                        </h2>
                        <div id="flush-collapseOne" class="accordion-collapse collapse"
                            aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body">{{product.product_description}}</div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapseTwo" aria-expanded="false"
                                aria-controls="flush-collapseTwo">
                                Shipping & Returns
                            </button>
                        </h2>
                        <div id="flush-collapseTwo" class="accordion-collapse collapse"
                            aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body">Placeholder content for this accordion, which is intended to
                                demonstrate the <code>.accordion-flush</code> class. This is the second item's
                                accordion body. Let's imagine this being filled with some actual content.</div>
                        </div>
                    </div>
                    <!-- <div class="accordion-item">
                      <h2 class="accordion-header" id="flush-headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                          Accordion Item #3
                        </button>
                      </h2>
                      <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the third item's accordion body. Nothing more exciting happening here in terms of content, but just filling up the space to make it look, at least at first glance, a bit more representative of how this would look in a real-world application.</div>
                      </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</section>
<div class="whatsapp-btn text-center d-flex justify-content-center align-items-center">
    <a href="https://wa.me/+918590366431" class="text-center d-flex justify-content-center align-items-center"><i class="fab fa-whatsapp text-light" style="font-size: 2.7rem;"></i></a>
  </div>
<!-- <script>
    document.getElementById('product_color').addEventListener('change', function() {
        var imageUrl = this.id;
        console.log('Selected image URL:', imageUrl); // Debugging line
        var image = document.getElementById('ProPurImage');
        image.src = imageUrl;
    });
</script> -->

{% endblock %}

VolantProject/VolantApp/templates/TandC.html
<!doctype html>
<html lang="en">
    <head>
        <title>Terms & Conditions</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
    <link rel="icon" href="./assets/images/favicon.ico">

        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <h2><strong>Terms and Conditions</strong></h2>

<p>Welcome to volantfootwear.com!</p>

<p>These terms and conditions outline the rules and regulations for the use of volant shoes pvt Ltd's Website, located at https://www.volantfootwear.com/.</p>

<p>By accessing this website we assume you accept these terms and conditions. Do not continue to use volantfootwear.com if you do not agree to take all of the terms and conditions stated on this page.</p>

<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company's terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client's needs in respect of provision of the Company's stated services, in accordance with and subject to, prevailing law of af. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>

<h3><strong>Cookies</strong></h3>

<p>We employ the use of cookies. By accessing volantfootwear.com, you agreed to use cookies in agreement with the volant shoes pvt Ltd's Privacy Policy. </p>

<p>Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p>

<h3><strong>License</strong></h3>

<p>Unless otherwise stated, volant shoes pvt Ltd and/or its licensors own the intellectual property rights for all material on volantfootwear.com. All intellectual property rights are reserved. You may access this from volantfootwear.com for your own personal use subjected to restrictions set in these terms and conditions.</p>

<p>You must not:</p>
<ul>
    <li>Republish material from volantfootwear.com</li>
    <li>Sell, rent or sub-license material from volantfootwear.com</li>
    <li>Reproduce, duplicate or copy material from volantfootwear.com</li>
    <li>Redistribute content from volantfootwear.com</li>
</ul>

<p>This Agreement shall begin on the date hereof. Our Terms and Conditions were created with the help of the <a href="https://www.termsandconditionsgenerator.com/">Free Terms and Conditions Generator</a>.</p>

<p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. volant shoes pvt Ltd does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of volant shoes pvt Ltd,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, volant shoes pvt Ltd shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p>

<p>volant shoes pvt Ltd reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</p>

<p>You warrant and represent that:</p>

<ul>
    <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>
    <li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>
    <li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>
    <li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>
</ul>

<p>You hereby grant volant shoes pvt Ltd a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p>

<h3><strong>Hyperlinking to our Content</strong></h3>

<p>The following organizations may link to our Website without prior written approval:</p>

<ul>
    <li>Government agencies;</li>
    <li>Search engines;</li>
    <li>News organizations;</li>
    <li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>
    <li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</li>
</ul>

<p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party's site.</p>

<p>We may consider and approve other link requests from the following types of organizations:</p>

<ul>
    <li>commonly-known consumer and/or business information sources;</li>
    <li>dot.com community sites;</li>
    <li>associations or other groups representing charities;</li>
    <li>online directory distributors;</li>
    <li>internet portals;</li>
    <li>accounting, law and consulting firms; and</li>
    <li>educational institutions and trade associations.</li>
</ul>

<p>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of volant shoes pvt Ltd; and (d) the link is in the context of general resource information.</p>

<p>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party's site.</p>

<p>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to volant shoes pvt Ltd. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</p>

<p>Approved organizations may hyperlink to our Website as follows:</p>

<ul>
    <li>By use of our corporate name; or</li>
    <li>By use of the uniform resource locator being linked to; or</li>
    <li>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party's site.</li>
</ul>

<p>No use of volant shoes pvt Ltd's logo or other artwork will be allowed for linking absent a trademark license agreement.</p>

<h3><strong>iFrames</strong></h3>

<p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p>

<h3><strong>Content Liability</strong></h3>

<p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p>

<h3><strong>Reservation of Rights</strong></h3>

<p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it's linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p>

<h3><strong>Removal of links from our website</strong></h3>

<p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</p>

<p>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p>

<h3><strong>Disclaimer</strong></h3>

<p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p>

<ul>
    <li>limit or exclude our or your liability for death or personal injury;</li>
    <li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
    <li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
    <li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
</ul>

<p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</p>

<p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>

        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

VolantProject/VolantApp/templates/adminaddsize.html
{% extends 'adminproducts.html' %}

{% block content %}
{{product}}
<h4 class="text-capitalize text-center">{{product.product_types}} {{product.product_category}} {{product.product_name}}</h4>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <button class="btn btn-outline-dark mt-3">Save</button>
</form>
<section>
    <div class="row">
        <h4 class="text-center text-black-50 py-4">Available sizes</h4>
        <table class="table table-stripped">
            <tr>
                <td>Size</td>
                <td>action</td>
            </tr>
            {% for i in sizes %}
            <tr>
                <td>{{i.size}}</td>
                <td><a href="" class="btn btn-danger">Delete</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</section>
{% endblock  %}